# Generated by Django 4.2.3 on 2023-07-18 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_publish', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
