# Generated by Django 4.2.3 on 2023-07-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hihi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='vk_id',
            field=models.CharField(default='404', max_length=255),
        ),
    ]
